TileMill.templates['layers']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'layers\'> <div class=\'sidebar-header clearfix pane\'> <h2>Layers</h2> <a href="#layers-add" id="layers-add">+ Add</a> </div> <ul class="sidebar-content"> </ul> </div> ');}return p.join(''); }
TileMill.templates['map']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'map-preview\'> <a class="map-fullscreen" href="#map-fullscreen">Fullscreen</a> <h4 id="zoom-display">Zoom level ?</h4> </div> ');}return p.join(''); }
TileMill.templates['popup']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id="popup"> <div class="popup-backdrop"></div> <div class="popup"> <div class="popup-header clearfix pane"> <h2>', title ,'</h2> <a href="#" class="popup-close">Close</a> </div> <div class="popup-content"></div> </div> </div> ');}return p.join(''); }
TileMill.templates['color-swatch']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <a href=\'#\' class=\'swatch\' style=\'background-color: ', color ,'\'><label>', color ,'</label></a> ');}return p.join(''); }
TileMill.templates['popup-layer']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'popup-layer\' class=\'clearfix pane\'> <form> <div><label for="classes">Classes</label><input type="text" class="text" id="classes"/></div> <div><label for="id">Id</label><input type="text" class="text" id="id"/></div> <div><label for="dataSource">Data Source</label><input type="text" class="text" id="dataSource"/></div> <div> <label for="srs">SRS</label> <select id="srs"> <option value="900913">900913</option> <option value="WGS84">WGS84</option> </select> </div> <div class="buttons"><input class="submit" type="submit" value="', submit ,'"/></div> </form> </div> ');}return p.join(''); }
TileMill.templates['column']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div class=\'column\'> <h2 class=\'pane\'>', name ,'</h2> <ul class="items"> '); for (i in data) { p.push(' <li><a href="#action=', type ,'&id=', data[i] ,'" class="route">', data[i] ,'</a></li> '); } p.push(' <li><form id="', type ,'"><input class="text" type="text"/><input class="submit" type="submit" value="Add ', type ,'"/></form></li> </ul> </div> ');}return p.join(''); }
TileMill.templates['list']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'header\' class=\'clearfix pane\'> <h1>TileMill</h1> </div> <div id="content" class="clearfix"> ', projects ,' ', visualizations ,' </div> </div> ');}return p.join(''); }
TileMill.templates['popup-standard']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'popup-standard\' class=\'clearfix pane\'> ', content ,' </div> ');}return p.join(''); }
TileMill.templates['project']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'header\' class=\'clearfix pane\'> <h1>Editing ', id ,'</h1> <a class="info" href="#project-info">Info</a> <a class="save" href="#project-save">Save</a> <a class="home" href="#list">Back home</a> </div> <div id="sidebar"> </div> ');}return p.join(''); }
TileMill.templates['color']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'color-palette\' class=\'pane\'> <div id=\'color-picker\' class=\'pane\'> <a class=\'color-picker\' href=\'#color-picker\'>Color picker</a> <input size="7" maxlength="7" id="color" type="text" class="text"/> <div class="pane" id="farbtastic"></div> </div> <div id="colors"> <label>Colors</label> <div></div> </div> </div> ');}return p.join(''); }
TileMill.templates['popup-stylesheet']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'popup-stylesheet\' class=\'clearfix pane\'> <form> <div><label for=\'stylesheet-name\'>Name</label><input id="stylesheet-name" class="text" type="text"/></div> <div class="buttons"><input class="submit" type="submit" value="Add stylesheet"/></div> </form> </div> ');}return p.join(''); }
TileMill.templates['stylesheets']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'tabs\'> <div class=\'stylesheets\'></div> <a class="tab-add" href="#">Add MSS</a> </div> <div id="editor"> <textarea id="code"></textarea> </div> ');}return p.join(''); }
TileMill.templates['popup-info']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'popup-info\' class=\'clearfix pane\'> <form> <div><label for=\'tilelive-url\'>TileLive URL</label><input id="tilelive-url" class="text" type="text" value="', tilelive_url ,'"/></div> <div><label for="mml-url">MML URL</label><input id="mml-url" class="text" type="text" value="', mml_url ,'"/></div> </form> </div> ');}return p.join(''); }
TileMill.templates['inspector']=function(obj) {var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push(' <div id=\'inspector\'> <div class=\'sidebar-header clearfix pane\'> <h2>Inspector</h2> <a class="inspector-close" href="#">Close</a> </div> <ul class="sidebar-content"> </ul> </div> ');}return p.join(''); }
